// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXr3U5uyNgbWUcRbpn5OEvGI3YeKs0Uvs',
    appId: '1:693025849380:web:b77b8d5e64956e520698b1',
    messagingSenderId: '693025849380',
    projectId: 'caremateapp',
    authDomain: 'caremateapp.firebaseapp.com',
    storageBucket: 'caremateapp.appspot.com',
    measurementId: 'G-RC5QC860HM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3Qnn6TVKg8ys7gJsNFhRcG5mPzKR5v1s',
    appId: '1:693025849380:android:6cdfced9ef10e2cb0698b1',
    messagingSenderId: '693025849380',
    projectId: 'caremateapp',
    storageBucket: 'caremateapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCs95DqyFpsxzfxbJQ_0d5We027LvIz7eg',
    appId: '1:693025849380:ios:f9bac501ead934810698b1',
    messagingSenderId: '693025849380',
    projectId: 'caremateapp',
    storageBucket: 'caremateapp.appspot.com',
    iosBundleId: 'com.example.caremateScreen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCs95DqyFpsxzfxbJQ_0d5We027LvIz7eg',
    appId: '1:693025849380:ios:f9bac501ead934810698b1',
    messagingSenderId: '693025849380',
    projectId: 'caremateapp',
    storageBucket: 'caremateapp.appspot.com',
    iosBundleId: 'com.example.caremateScreen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXr3U5uyNgbWUcRbpn5OEvGI3YeKs0Uvs',
    appId: '1:693025849380:web:f44c1ad0918ad1d80698b1',
    messagingSenderId: '693025849380',
    projectId: 'caremateapp',
    authDomain: 'caremateapp.firebaseapp.com',
    storageBucket: 'caremateapp.appspot.com',
    measurementId: 'G-FK7LQFPRP4',
  );
}
